---
# tasks file for simplestack
- name: Install requisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - bridge-utils
    - qemu-utils
    - libguestfs-tools
    - uml-utilities
    - ethtool
    - unzip
    - vlan
- name: Install simplestack
  unarchive:
    src: https://dl.bintray.com/activatedio/releases/simplestack_0.0.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: True
- name: Setup kvm users
  user:
    name: "{{ item }}"
    groups: kvm
  with_items: "{{ simplestack.users }}"
- name: Setup vlan interfaces
  template:
    src: interfaces.d/vlan.j2
    dest: "/etc/network/interfaces.d/{{item.interface_name}}.{{item.vlan_name}}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ simplestack.interfaces }}"


