---
# tasks file for simplestack
- name: Install requisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - bridge-utils
    - qemu-utils
    - libguestfs-tools
    - uml-utilities
    - ethtool
    - unzip
    - vlan
- name: Install simplestack
  unarchive:
    src: "https://dl.bintray.com/activatedio/releases/simplestack_{{ simplestack_version }}_{{ simplestack_arch }}.zip"
    dest: /usr/local/bin
    remote_src: True
    creates: /usr/local/bin/simplestack
- name: Setup kvm users
  user:
    name: "{{ item }}"
    groups: kvm
  with_items: "{{ simplestack_users }}"
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
- name: Setup vlan interfaces
  template:
    src: interfaces.d/vlan.j2
    dest: "/etc/network/interfaces.d/vlan"
    owner: root
    group: root
    mode: 0644
  when: simplestack_interface_name is defined
  notify:
    - restart networking

