---
- hosts: all
  pre_tasks:
    - name: Create stack user
      user: 
        name: stack
  roles:
    - role: ansible-simplestack
  vars:
    simplestack:
      users:
        - stack
      interfaces:
        - interface_name: enp0s25
          vlan_name: 102
          address: 34.33.33.1
          netmask: 255.255.255.0
